### ISSUE TITLE
No mention of YTPlayerView-iframe-player.html in documentation.

### ISSUE THREAD

**Issue by Baza207** [youtube/youtube-ios-player-helper#1]
There should probably be something in the [documentation](https://developers.google.com/youtube/v3/guides/ios_youtube_helper) about the fact that as well as `YTPlayerView.h` and `YTPlayerView.m` you also need `YTPlayerView-iframe-player.html` as well in you're project.

This is of course if you import without using CocoaPods, which a lot of people still do.

Either this or this html file should be hard coded into `YTPlayerView.m` when it creates and loads the webView.

I don't know whether this is the right place for this, but it has the possibility to be a fix in code.

**Comment by zmorris** [comment]
Just lost a couple of hours to this.  I have this in my Podfile:

pod 'youtube-ios-player-helper', '~> 0.1.5'

But it doesn't install YTPlayerView-iframe-player.html at <build-products>/youtube_ios_player_helper.framework/Assets/YTPlayerView-iframe-player.html like it should, so I had to make a manual Copy Files Build Phase which is irksome.  It looks like Assets.bundle doesn't get added to my Pods even though it's in the Development Pods of youtube-player-ios-example but I don't understand why yet.

**Comment by darthpelo** [comment]
I have the same issue, as @zmorris.
Updated the pod, but no Assets...

**Comment by JALsnipe** [comment]
http://stackoverflow.com/a/34904245/2415822

**Comment by darthpelo** [comment]
Thanks @JALsnipe you were faster than me :) 
I found this, looking better: https://github.com/youtube/youtube-ios-player-helper/issues/160

**Comment by zmorris** [comment]
Also thanks @JALsnipe, [your comment](https://github.com/youtube/youtube-ios-player-helper/issues/1#issuecomment-178643475) fixed it for me as well, and I was able to remove YTPlayerView-iframe-player.html from my project and take its copy files build phase out of my project settings.
