### ISSUE TITLE
No fullscreen button on the toolbar

### ISSUE THREAD

**Issue by RajeshReddy** [youtube/youtube-ios-player-helper#105]
Thanks a lot for an awesome player, I am using it in my iOS app. Everything went fine until the fullscreen button on the toolbar of the youtube player got disappeared, now I don't see the fullscreen button. 
![screen shot 2015-05-24 at 2 23 20 pm](https://cloud.githubusercontent.com/assets/2758766/7787263/8a4ac96c-0220-11e5-805c-6458fa0b99f2.png)
Instead I have a video quality button, playlist button and play on youtube button which are not much useful for me, also which weren't there before. So how to get a fullscreen button on the toolbar and if possible how to remove unwanted buttons. Should I have to change anything in the html file?  Thanks in advance.

**Comment by jbolter** [comment]
Same issue here.  No changes on our end so something must have changed in the YouTube JS.

**Comment by RajeshReddy** [comment]
The issue got fixed...! Think Youtube's fault.
