### ISSUE TITLE
OAuth redirect when playing some Live Events

### ISSUE THREAD

**Issue by JALsnipe** [youtube/youtube-ios-player-helper#109]
Relevant StackOverflow link: http://stackoverflow.com/questions/30482280/ytplayer-will-redirect-to-oauth2-url-and-shows-please-stand-by

I'm trying to play this Live Event in the YTPlayerView: https://www.youtube.com/watch?v=w-T2LJ_qLiw

At first, the webview tries to load the video URL, which is normal:

https://www.youtube.com/embed/w-T2LJ_qLiw?modestbranding=1&showinfo=0&rel=0&playsinline=1&controls=1&enablejsapi=1

Then, the player tries to load this weird OAuth URL:

https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fwww.youtube.com#rpctoken={TOKEN}&forcesecure=1

After that, the player tries to load this static/proxy.html URL:

https://content.googleapis.com/static/proxy.html?jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.dPxK-DAj_pE.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTN0fuoBkyFaoHWfzWWLct0BxZgQSQ#parent=https%3A%2F%2Fwww.youtube.com&rpctoken={TOKEN}

Both URLs take the user out of the app and into Safari.  I have tried adding a regex to stop the webview from kicking the user out to safari, similar to the way ads are handled:

```obj-c
NSString static *const kYTPlayerOAuthRegexPattern = @"^http(s)://accounts.google.com/o/oauth2/(.*)$";
NSString static *const kYTPlayerStaticProxyRegexPattern = @"^https://content.googleapis.com/static/proxy.html(.*)$";

// ...

- (BOOL)handleHttpNavigationToUrl:(NSURL *) url {
    // Usually this means the user has clicked on the YouTube logo or an error message in the
    // player. Most URLs should open in the browser. The only http(s) URL that should open in this
    // UIWebView is the URL for the embed, which is of the format:
    //     http(s)://www.youtube.com/embed/[VIDEO ID]?[PARAMETERS]
    
    // ...
    
    NSRegularExpression *oauthRegex =
    [NSRegularExpression regularExpressionWithPattern:kYTPlayerOAuthRegexPattern
                                              options:NSRegularExpressionCaseInsensitive
                                                error:&error];
    NSTextCheckingResult *oauthMatch =
    [oauthRegex firstMatchInString:url.absoluteString
                           options:0
                             range:NSMakeRange(0, [url.absoluteString length])];
    
    NSRegularExpression *staticProxyRegex =
    [NSRegularExpression regularExpressionWithPattern:kYTPlayerStaticProxyRegexPattern
                                              options:NSRegularExpressionCaseInsensitive
                                                error:&error];
    NSTextCheckingResult *staticProxyMatch =
    [staticProxyRegex firstMatchInString:url.absoluteString
                           options:0
                             range:NSMakeRange(0, [url.absoluteString length])];
    
    if (ytMatch || adMatch || oauthMatch || staticProxyMatch) {
        return YES;
    } else {
        [[UIApplication sharedApplication] openURL:url];
        return NO;
    }
}

```

But even after forcing the video to load, I just get "An error has occurred" with the `receivedError` delegate not called.

![screen shot 2015-05-27 at 9 56 35 am](https://cloud.githubusercontent.com/assets/4513736/7837721/d1915e8e-0456-11e5-90e7-9c5913a42866.png)

Is OAuth or HTTPS required for some live events?  Is this new live event not supported by the iFrame API?

**Comment by JALsnipe** [comment]
Something must have changed on Google's end.  This is now working.

**Comment by JungHoonLee** [comment]
@JALsnipe  It's currently not working for me. is it still working for you?

**Comment by JungHoonLee** [comment]
@JALsnipe it's working now. Thanks

**Comment by dewsxc** [comment]
Hi, redirect to OAuth2 still happened now event use sample code, 
is there any solution that can work around?

**Comment by dewsxc** [comment]
A solution for this situation by stop app jump to Sarfari.
Wipe out method content from YTPlayerView.m
- (BOOL)handleHttpNavigationToUrl:(NSURL *) url {
    .....
}
to 
return YES.

**Comment by JALsnipe** [comment]
@dewsxc can you provide a Video ID that still causes this redirect?

**Comment by dewsxc** [comment]
Any video is live event. Like "nrYHu7hmMK0", "wpZNaYN29xs" etc.

**Comment by JALsnipe** [comment]
Thanks @dewsxc.  I have opened #111 to fix this issue.

**Comment by JALsnipe** [comment]
#111 has been merged!  Closing this issue.
