### ISSUE TITLE
Fullscreen controls won't show up

### ISSUE THREAD

**Issue by Lukaz32** [youtube/youtube-ios-player-helper#112]
I've set up a YTPlayerView outlet but I can't find the fullscreen control button. It just won't show up. If I tap it once it pauses the video and the pinch gesture does nothing.
I'm building on an iPhone 6 with iOS 8.3. What might be going on?
![img](https://cloud.githubusercontent.com/assets/544727/7945562/f9bdd7e8-0947-11e5-87c8-6cc83c7908a7.png)

**Comment by JALsnipe** [comment]
Are you using any `playerVars`?  If so, post them.

**Comment by Lukaz32** [comment]
I've used the default ones.
`NSDictionary *playerVars = @{
      @"controls" : @0,
      @"playsinline" : @1,
      @"autohide" : @1,
      @"showinfo" : @0,
      @"modestbranding" : @1
  };`

**Comment by Lukaz32** [comment]
Oh, that's embarrassing. Apparently setting controls to `1 already shows up the missing items.

Thank you. 👍

**Comment by JALsnipe** [comment]
You need to set the key for `controls` to `@1`.
