### ISSUE TITLE
Setting @"origin" breaks JSAPI functionality

### ISSUE THREAD

**Issue by hawkwood** [youtube/youtube-ios-player-helper#121]
If I add the line:
    `@"origin": @"example.com", `
before:
    `@"modestbranding": @1`
at line 30 in `SingleVideoViewController.m`, and the programatic controls no longer function to affect the video, and the progress bar no longer updates.  Additionally, very few of the status messages are being shows/received.

I assume/hope "origin" would show up in analytics, to signify source, which is why I'm setting it.

**Comment by JALsnipe** [comment]
Reposting from StackOverflow: http://stackoverflow.com/a/31029514/2415822

You are not passing in a valid url for the `origin` parameter.

Try `@"origin": @"https://example.com"` or `@"origin": @"http://example.com"`.  Note the `http(s)://`.

**Comment by ErikAGriffin** [comment]
I have this same issue, and my origin parameter is properly formatted "https://example.com"
