### ISSUE TITLE
remove reference form control center

### ISSUE THREAD

**Issue by MiaShopgal** [youtube/youtube-ios-player-helper#126]
we provide user to play multi-source music in our app, so he could find all the music he likes in one place.

it would be all good if user only plays the albums he bought from the iTunes. 

when he played lots youtube video, as many AVPlayerItem will be created as well, and sent to control center.

then user leave the app to home screen, music from the video stop which is very natural.
call the control center and hit play, all the video he played will play all at once, it would be too rich for the user, is there any way we could do to avoid this kind of scenario ?

**Comment by MiaShopgal** [comment]
I just figure out that we need to call stopVideo while entering home screen
but the MPNowPlayingInfoCenter still shows the info of the video in a blinking style..

**Comment by ArkReversed** [comment]
+1

**Comment by ArkReversed** [comment]
It's not optimal at all to have this functionality enabled by default imo.

**Comment by MiaShopgal** [comment]
turns out it's the javascript of the web does the work for registering remote control 
use swizzling to filter will do the work

**Comment by ArkReversed** [comment]
Can you share the code snippet that fixes this?

**Comment by MiaShopgal** [comment]
@DaidoujiChen and I have putting it in below, please refer to it.
https://github.com/DaidoujiChen/HelloJukeBox.git

**Comment by ArkReversed** [comment]
Swizzling is indeed a great way to deal with this. Thanks ;)
