### ISSUE TITLE
podspec needs to be updated to 0.1.4

### ISSUE THREAD

**Issue by BluMist** [youtube/youtube-ios-player-helper#129]
I noticed that Cocoapod spec does not yet reference the latest version. Please update?

**Comment by ArkReversed** [comment]
+1

**Comment by MontakOleg** [comment]
+1

**Comment by asivura** [comment]
+1

**Comment by drichardson** [comment]
I can't believe no one has `pod trunk push` yet. Well, in the meantime, you can get 0.1.4 by putting the following line in your Podfile:

    pod 'youtube-ios-player-helper', git: 'https://github.com/youtube/youtube-ios-player-helper.git', :tag => '0.1.4'

But note that will tie you to 0.1.4 indefinitely. Running `pod update` will no longer take you to the next released version.
