### ISSUE TITLE
Can't pause on iOS 9

### ISSUE THREAD

**Issue by ArkReversed** [youtube/youtube-ios-player-helper#130]
Hi

Have you guys tested this helper on iOS 9 yet? For some strange reason, pausing playback doesn't seem to work for me. Other actions work just fine. 

I'm using the current XCode 6.4, compiling for iOS8 and simply installing the through testflight on a iOS9 (public beta) phone.

**Comment by akupila** [comment]
Looks like this was a problem in iOS9 and has been fixed in iOS9 beta 4 (released July 21). Without any changes pause now works as expected.

**Comment by ArkReversed** [comment]
You are right, the beta 4 fixed this. Let's hope it does not regress in the future. 

Closing.
