### ISSUE TITLE
showinfo=0 & modestbranding=1 are not working together

### ISSUE THREAD

**Issue by MindTheGap** [youtube/youtube-ios-player-helper#135]
Hi,

I wanted to not show youtube's logo at the bottom right and also to not show the title of the video. apparently, this isn't possible with these 2 flags.

I really think I'm not but perhaps I'm missing something?

Thanks!

**Comment by MiaShopgal** [comment]
by setting showinfo=0 could make the title bar gone

the youtube logo at the bottom-right corner will remain shown when the video is paused, despite the value of modestbranding is 0 or 1

https://developers.google.com/youtube/player_parameters#modestbranding

**Comment by MindTheGap** [comment]
I don't follow. 

The player parameters (with the link you attached) are stating very clearly that a youtube's logo should still appear on the upper-right (!) corner but the bottom-right corner should be hidden.

"Note that a small YouTube text label will still display in the upper-right corner of a paused video when the user's mouse pointer hovers over the player."

**Comment by MiaShopgal** [comment]
the documentation might out of date about the upper-right, cos the test I've done shows this 

showing=1, modestbranding=0 there's a "YouTube" text with underscore 
![showing=1, modestbranding=0](http://i.imgur.com/8cpBNi1.png)
showing=1, modestbranding=1 underscore text is gone
![showing=1, modestbranding=1](http://i.imgur.com/LFOoETw.png)

showing=0, modestbranding=1
showing=0, modestbranding=0 bottom right logo remains
![showing=0](http://i.imgur.com/oiNOnXS.png)

**Comment by MindTheGap** [comment]
Oh.. I never thought that the documentation might be outdated.

Thank you very much for your kind help!

**Comment by JackHasaKeyboard** [comment]
You can always just nullify it on your end via CSS or something.

**Comment by kalpeshjjethva** [comment]
can I hide the youtube marker from the video?

**Comment by birendra2016** [comment]
modestbranding=1 not working, anyone help

**Comment by prashanthc** [comment]
@JackHasaKeyboard , because of the cross-domain policy, we cannot access the DOM elements of the video.  Due to this we can't apply the CSS stylings to hide them. By applying any of the parameters from their API, one way or the other it atleast displays one link which will re-direct to the original source video on youtube.

**Comment by webashraf** [comment]
showinfo=0 is not working any one please help me.
