### ISSUE TITLE
Cocoa error 258

### ISSUE THREAD

**Issue by raginggoat** [youtube/youtube-ios-player-helper#15]
When loading my view, I get this error:

Received error rendering template: Error Domain=NSCocoaErrorDomain Code=258 "The operation couldn’t be completed. (Cocoa error 258.)"

**Comment by rrallo** [comment]
Running into this issue. Did you just add the reference to the file in the 'copy bundle resources' section?

**Comment by JALsnipe** [comment]
See the discussion here:

http://stackoverflow.com/questions/23751817/try-to-play-you-tube-video-with-ytplayer-third-partry-libraray-in-ios

**Comment by BhavinBhadani** [comment]
I am using swift...and manually install library... as said in manual guide. i copy folders and files with checkmark of `copy if needed` and `references` but it gives me error unable to find `YTPlayerView.h` in my bridging-header file....then i'll try to install it without `copy if needed` and `references`...and the error resolved but i got the error #258 when playing the video...i gave a path like....  
      
       let path = NSBundle.mainBundle().pathForResource("YTPlayerView-iframe-player", ofType: "html")  

but it wont work ...so how to resolve this

**Comment by whitelionV** [comment]
Make sure `YTPlayerView-iframe-player.html` is copied into your Xcode project and it appears in Settings -> Build Settings -> Copy Bundle Resources.
