### ISSUE TITLE
Release 0.1.5 doesn't include Assets

### ISSUE THREAD

**Issue by scatterbrain** [youtube/youtube-ios-player-helper#157]
It seems like the 0.1.5 release doesn't include the Assets folder anymore when installing with CocoaPods as a framework. 

This causes error 258 when trying to use the view because the YTPlayerView-iframe-player.html is not available. 

```
$ ls Pods/youtube-ios-player-helper
Classes   LICENSE   README.md
```

My Podfile: 
```
platform :ios, '8.0'
use_frameworks!

target 'testproject' do
    pod "youtube-ios-player-helper", "0.1.5"
end
```

**Comment by ibrahimennafaa** [comment]
Related issue for me when running *pod install* : 
`[!] An unexpected version directory 'Assets.bundle' was encountered for the '/Users/ibrahimennafaa/.cocoapods/repos/youtube/youtube-ios-player-helper' Pod in the 'youtube-ios-player-helper' repository.`

**Comment by Wojdan** [comment]
On **master**, there is a directory called **youtube-ios-player-helper**. For me, dragging and dropping its contents into sample project solved the issue (error 258). It should be included in the release 1.5.0 out of hand, though.

**Comment by maxoly** [comment]
+1

**Comment by JALsnipe** [comment]
@Wojdan that defeats the purpose of Cocoapods.

**Comment by iGranDav** [comment]
Until this issue is resolved you can force CocoaPods using the previous version with `pod 'youtube-ios-player-helper', '= 0.1.4'`

**Comment by neirar** [comment]
Either the Assets folder needs to be created again with the HTML file in it, or the Podspec needs to be updated. 

By the way, according to the CocoaPods documentation (https://guides.cocoapods.org/syntax/podspec.html#resource_bundles), the resource bundle names should "at least include the name of the Pod to minimise the chance of name collisions". The name in the specs file is just "Assets" and it should be something like "YouTubeiOSPlayerHelperAssets".

**Comment by btelintelo** [comment]
Never use the ~ in cocoapods .  This is just beta software afterall

**Comment by jose920405** [comment]
+1
