### ISSUE TITLE
Issue with UITableView

### ISSUE THREAD

**Issue by anoopmg** [youtube/youtube-ios-player-helper#173]
Loading YTPlayer in table cell,when scrolling device(ios 9) stuck(hang) for 5-10 minutes.
 NSDictionary *playerVars = @{
                                     @"playsinline" : @1,
                                     };
[self.m_vwVideoContainer loadWithVideoId:IN_objCardDetails.m_arrContent[0]  playerVars:playerVars];

For resolving this issue we load the thumbnail only, then the scrolling issue is fixed. But when we tap on the youtube video frame, we lost all the tableview delegates for that cell(didnt fire the event like "cellForRowAtIndexPath","didSelectRowAtIndexPath","didEndDisplayingCell").

Please help me to solve any of the above issues.

**Comment by tww0003** [comment]
@anoopmg I see you closed this issue. I'm having the same problem of tableview delegate methods not firing on the cell when a video is playing. Did you manage to fix it? If you did, can you tell me how?
