### ISSUE TITLE
Mute not working

### ISSUE THREAD

**Issue by santihbc** [youtube/youtube-ios-player-helper#20]
Muting the video programmatically doesn't work. Is there any way to accomplish that?

**Comment by itsthejb** [comment]
I think the OP is referring to use the Javascript functions `player.setVolume(...)` or `player.mute()`. These don't appear to do anything, though...

**Comment by okankocyigit** [comment]
https://stackoverflow.com/questions/37290108/how-to-play-youtube-video-in-uiwebview-muted#37315071

this hacky method is working well for me.
