### ISSUE TITLE
Remove the video title link and share icon

### ISSUE THREAD

**Issue by axl163** [youtube/youtube-ios-player-helper#209]
This is more of a question. Is there a way to unlink the title video from linking to the YouTube video? Also, I would like to remove the share icon altogether and possible replace it with something that is not as pixelated. Thank you!

**Comment by axl163** [comment]
I found the solution to question. I can pass the 'showinfo' param to the view:

https://developers.google.com/youtube/player_parameters

**Comment by ankit0812** [comment]
@axl163 Does not work now?
Anywork around that you have came up with?

**Comment by arihantja1n** [comment]
doesn't work now

**Comment by anshulmahipal** [comment]
Show Info has deprecated anyone has other solution

**Comment by KaranMehta3984** [comment]
> Show Info has deprecated anyone has other solution

Have you got any solution?

**Comment by KaranMehta3984** [comment]
@anshulmahipal 
Have you got any solution?
