### ISSUE TITLE
iOS 10 playing inline doesn't work on device

### ISSUE THREAD

**Issue by Muesly** [youtube/youtube-ios-player-helper#218]
I'm finding that videos are not playing inline on my iPhone 6 with iOS 10 beta 5 installed, but they work on the simulator.  On the device it brings up the full screen video display.

I believe this is a new change by Apple as an earlier beta didn't show this behaviour.

I am using the call 	

[self.playerView loadWithVideoId:@"M7lc1UVf-VE" playerVars:@{ @"playsinline" : @(1) }];

Any ideas how to resolve?

**Comment by noobs2ninjas** [comment]
Any luck? I just upgraded to beta 5 for testing and was about to begin when I noticed this issue.

**Comment by noobs2ninjas** [comment]
I just discovered something. The video isn't not playing inline. Sounds weird but ill explain. There is two arrows pointing towards each other in the bottom right hand corner that if hit closes the video down to its original size and continues in-line. As opposed to traditional full screen where full-size will stop playing when closed.

**Comment by noobs2ninjas** [comment]
https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

>Inline and Auto Video Playback on iOS
>- When the webkit-playsinline property is specified, Safari on iPhone allows videos to play inline. >Videos without the property will commence playback in fullscreen, but users can pinch close on >the video to continue playing the video inline.
>- On iOS, videos without audio tracks or with disabled audio tracks can play automatically when >the webpage loads.

**Comment by Muesly** [comment]
Thanks - I think you're right, YouTube's javascript library needs to call playsinline attribute too.  The WebKit link says 'the prefixed attribute will work' but maybe that has already been deprecated.

**Comment by mqueens** [comment]
This is fixed as of today!

**Comment by MamdouhRElNakeeb** [comment]
This fixed the issue for me, it controls the embedded **webView** and play it **inline**.
`youtubePlayer.load(withVideoId: videoID, playerVars: ["playInline" : 1])`
