### ISSUE TITLE
This video contains content from VEVO. It is restricted from playback on certain sites.

### ISSUE THREAD

**Issue by iamharshilsoni** [youtube/youtube-ios-player-helper#24]
video id  CcK9Q9rLcbU ...... the above error ...... how to solve it  ?

**Comment by atulvuliv** [comment]
Add `player vars` while initializing youtube sdk:
    NSDictionary *playerVars = @{
                                 @"origin" : @"http://www.youtube.com",
                                 };
    [self.playerView loadWithVideoId:@"KOvoD1upTxM" playerVars:playerVars];

Enjoy!

**Comment by alex3144** [comment]
so it's possible to play Vevo content outside youtube player ? :)
