### ISSUE TITLE
Player gets muted when ringer is silenced.

### ISSUE THREAD

**Issue by sddhrthkum** [youtube/youtube-ios-player-helper#258]
When i silence the ringer using silence ringer button on iPhone the player gets muted. Making the ringer silent should not affect the player sound but it gets muted.

**Comment by dfmuir** [comment]
Add the code in to your AppDelegate didFinishLaunchingWithOptions method:

        do { try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback) } catch { } // videos will play even when the silent switch is enabled
