### ISSUE TITLE
Issue, during playing on real ios (11.2) device

### ISSUE THREAD

**Issue by RazKarapetyan** [youtube/youtube-ios-player-helper#296]
When i am trying to play youtube video on ios simulator, everything is fine.

But when i run my app on real ios device (ios 11.2) , youtube video is loading, 
but video doesn't play, seconds didn't increasing and no sound.

Do you know the reason of this problem, i couldn't find the solution :)

**Comment by aaasifrz9** [comment]
Same problem here. No sound.

**Comment by RazKarapetyan** [comment]
Solution for me:
Before playing video set audio session category to Playback
AVAudioSession* audioSession = [AVAudioSession sharedInstance];
[audioSession setCategory:AVAudioSessionCategoryPlayback  error:nil];

**Comment by aaasifrz9** [comment]
Thanks @RazKarapetyan. Its working.

**Comment by aaasifrz9** [comment]
Hi @RazKarapetyan , 
I need 1 more help that how to start video with auto play feature.
Please help. Thanks in advance.

**Comment by RazKarapetyan** [comment]
Hi ,

You need to implement delegate method for it:


in the viewDidLoad specify self.videoView.delegate to self and implement
this:


-(void)playerViewDidBecomeReady:(YTPlayerView *)playerView{

    [[NSNotificationCenter defaultCenter] postNotificationName:@"Playback
started" object:self];

    [self.videoView playVideo];

}


Also during playing video:

specify playerVars parameters like this:

 NSDictionary *playerVars = @{

                                @"autoplay" : @1,

                                @"origin" : @"http://www.youtube.com",

                                 };



 [self.videoView loadWithVideoId:id playerVars:playerVars];


Best regards,

Raz
