### ISSUE TITLE
How can i remove the share button and watch later button?

### ISSUE THREAD

**Issue by Eddiegooo** [youtube/youtube-ios-player-helper#333]
Can i remove the share button?  

 set @"showinfo" : @0,     it does not work!

**Comment by todd-patterson** [comment]
The "showinfo" parameter was deprecated on 2018-09-25, see announcement here -
https://developers.google.com/youtube/player_parameters#august-23,-2018

Unfortunately there is no alternative API to hide UI elements in the top region of the player.
