### ISSUE TITLE
Get error when play video (An error occurred. Please try again later. (Playback ID: xxxxxxxxx))

### ISSUE THREAD

**Issue by JeanC17** [youtube/youtube-ios-player-helper#334]
I'm getting error "An error occurred. Please try again later. (Playback ID: xxxxxxxxx)" when trying to play video.
Please note that it only happen on certain youtube and certain device.

Added origin parameter but still get the same error.

[self.playerView loadWithVideoId:videoId playerVars:@{
                                                          @"origin": originUrl,
                                                          @"playsinline" : @1
                                                          }];

**Comment by xuansang063** [comment]
I have same problem, can some one help me

**Comment by todd-patterson** [comment]
This type of issue is video-specific and outside the scope of "youtube-ios-player-helper" library. Nevertheless, here is some quick guidance:

There are a number of reasons a particular video or batch of videos may be in this state. In most cases the issue will be resolved automatically once the impacted video(s) are reprocessed. If your issue persists or seems generalized to all videos, please refer to the YouTube Help Center for support -
https://support.google.com/youtube/community

**Comment by SafoineMoncefAmine** [comment]
I have the same issue, @todd-patterson what do you mean by the issue will be resolved if it's reprocessed. Thanks.
