### ISSUE TITLE
iOS 13 & web view deprecation building for Mac

### ISSUE THREAD

**Issue by ManjitBedi** [youtube/youtube-ios-player-helper#347]
Is there an official solution from Google on building an iOS 13 app that will also work on a Mac using project Catalyst?

Using a Webview is  not available when compiling for a Mac target. 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIWebView", referenced from:
      objc-class-ref in YTPlayerView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by AliTariqQuantum** [comment]
UIWebView is also going to be deprecated for iOS 13 and onward. Is there going to be newer version of this project?

**Comment by bluelabeldeveloper1** [comment]
The App Store will no longer accept new apps using UIWebView as of April 2020 
Can you please update WKWebView instead of UIWebView

**Comment by islamshazly** [comment]
So is there any updates about issue, Im in that trap now!

**Comment by todd-patterson** [comment]
I'm not sure about Mac Catalyst specifically, but this library has now been updated to use WKWebView.

Please update to the official 1.0.0 release -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0
