### ISSUE TITLE
Make YTPlayerView fullscreen programatically

### ISSUE THREAD

**Issue by yadavharsh** [youtube/youtube-ios-player-helper#35]
Hi,

I am trying to make the player view full screen programmatically, but I am unable to do so.

Is there an exposed method in the api or a callback that can be used to accomplish this?

Thanks

**Comment by thidayatullah** [comment]
@JesusEspejo  : Your solution's work fine.  I use this same method in my app using AutoLayout, the only problem is every time I change the orientation the video is re-loading. 
I think the video will always reload everytime we change the youtube-player view frame / position either with code or auto layout.

Is there a way to make it continue the video smoothly without reloading?  I tried to pause it before the orientation change and resume it after the orientation is changed (and add delay) but it still doesn't work.

And please check the Youtube App on iOS, it have strange behaviour (delayed orientation change) but the video doesn't reload.

Here is my code :
```
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    [self.myVideoPlayer pauseVideo];
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext> context)
     {
         
     } completion:^(id<UIViewControllerTransitionCoordinatorContext> context)
     {

         UIInterfaceOrientation orientation = [[UIApplication sharedApplication] statusBarOrientation];
         // do whatever
         if(orientation == UIInterfaceOrientationLandscapeLeft || orientation == UIInterfaceOrientationLandscapeRight){
             [self.navigationController setNavigationBarHidden:YES animated:YES];
         }else{
             [self.navigationController setNavigationBarHidden:NO animated:YES];
         }
         [self performSelector:@selector(playVideo) withObject:nil afterDelay:1];

     }];
    
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
}
```

**Comment by JV17** [comment]
@thidayatullah it shouldn't reload when you change the frame... If you set the player parameters to play inline properly, it should work fine. I have it in example app playing inline and when I change to landscape, I resized the frame of the player to the entire screen to simulate a fullscreen mode and it doesn't reload or anything like that.. It keeps playing smoothly..

**Comment by thidayatullah** [comment]
@JV17 here is my code to load the video (I put it in viewDidLoad)
````
    NSDictionary *playerVars = @{
      @"controls" : @1,
      @"playsinline" : @1,
      @"autohide" : @1,
      @"showinfo" : @1,
      @"autoplay" : @0,
      @"fs" : @1,
      @"rel" : @0,
      @"loop" : @0,
      @"enablejsapi" : @1,
      @"modestbranding" : @1
      };
    [self.myVideoPlayer loadWithVideoId:currentClip.clip_video.video_media_id playerVars:playerVars];
```
Is there something I did wrong?
And thank you for your example app, definitely gonna check it !

**Comment by JV17** [comment]
Try this..
```
NSDictionary *playerVars = @{
      @"controls" : @"1",
      @"playsinline" : @"1",
      @"autohide" : @"1",
      @"showinfo" : @"1",
      @"autoplay" : @"0",
      @"fs" : @"1",
      @"rel" : @"0",
      @"loop" : @"0",
      @"enablejsapi" : @"1",
      @"modestbranding" : @"1",
      };
    [self.myVideoPlayer loadWithVideoId:currentClip.clip_video.video_media_id playerVars:playerVars];
```

**Comment by thidayatullah** [comment]
@JV17 : Tried it, still reloading.
And also I run your example app, and it is still reloading when I change the orientation.

Maybe I'm not stated it clearly in my first question -my bad-, I try to change the orientation without going to full screen mode.

So it goes like this: 
I played my video inline in portrait, and when I change it to landscape I RESIZE the player to fill the screen WITHOUT going to full screen mode that's when reloading happened.

**Comment by JV17** [comment]
@thidayatullah I just tested my example app and works fine for me.. it launches the player in inline and it keeps it like that unless you pressed the fullscreen button. When rotation happens keeps playing and resizes the frame.. This is in iOS 8, I haven't test it in iOS 7 or lower.. I will check those versions later on today. 

Btw, you shouldn't tell the player to pause or play if is already playing when doing the rotation and resizing it. I just saw that in the code ```viewWillTransitionToSize:``` of your previous comment.

**Comment by JV17** [comment]
@thidayatullah I just checked and looks like it happens in iPhone 6 devices and lower.. I will check it out, but I was testing it on an iPhone 6 Plus..

**Comment by Kowaio** [comment]
Hi @JV17,

I've got the same issue you discussed with @thidayatullah about the reloading video when changing the player view size (by rotating the device for instance).

Indeed, it seems the YT API forces the reloading when the resolution changes.
In my case, I start to load and play the video with params inline = 1, in portrait mode, on an iPhone 6 (so width=375 and height about 210px at that time with a 16/9 ratio). The YTPlayerView returns a quality of medium at first. I guess it is due to this low resolution.

As soon as I rotate the device and do the trick explains above to rotate the YTPlayerView and resize it to my whole screen (so w=667 h=375 in landscape mode for iPhone6), a BUFFERING state is called by the delegate and the quality is changed to hd720.

I currently can't find a way to force to hd720 even with a low resolution (height = 210 in my case).

Below are my lines in YTPlayerView-iframe-player.html:
    <head>
        <style>
           body { margin: 0; width:100%%; height:100%%; }
           html { width:100%%; height:100%%; }
        </style>
    </head>

I did that in order for me to have the video size always at the size of my YTPlayerView. It allows me, when rotating my device to landscape to update the video size to the view. I think this is the main cause of my issue.

Indeed, when I changed those lines with 1280px and 720px, for instance, it loads the video with quality = hd720 for both landscape and portrait mode. 

But the problem is that, since I forced the resolution to load a better quality, the video inside the YTPlayerView is also in 1280px and 720px and therefore is bigger than the view (which is still 375x210 in portrait, of course). So I kind of need those 100%% there...

I think I'm hitting a wall here.

If you've got (or anyone else) an input on this matter, it would be greatly appreciated :)

Thanks a lot,

My best regards,

**Comment by JV17** [comment]
@Kowaio Sorry, but I tried injecting js code and changing different parameters loading them to the player but not luck. Even tho, from my point of view the behaviour of the player is correct, because it avoids extra use of data when you are using the player over 3G/LTE.

**Comment by Kowaio** [comment]
Fair enough!

However, it seems weird that this works on a browser (google chrome for instance) and not in our case. Even if you're watching a video embed on a website with a low resolution, you still can change the quality to HD and watch it. It seems like the player or the API is blocking it. I understand "*the extra use of data*" matter, but it should detect if the connection is currently running on Wifi or phone network then. In any case, it could be great to force the quality regardless of the view resolution. Some videos are really quite short (less than 20 seconds) and I don't find it user-friendly to have the player reloading the view each time it goes into landscape or portrait.

**Comment by naveen488** [comment]
sry sir, I am added my question i think you know about how to play youtube videos playing while lock the screen. my problem is how to show progress bar while lock the screen?

pls help me sir..........

**Comment by glennposadas** [comment]
Hi everyone, I've read all of your comments here and apparently I got no absolute solution to the very question of the OP. I got the same question: How to programmatically make the player full screen (e.g. if I tap a UIButton, the screen goes full).???

Glenn

**Comment by KSelvam** [comment]
Take the height constraint reference of main view where player add as subview and use following code. This worked 100% for me


  override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // Register to receive notification
        NotificationCenter.default.addObserver(self, selector: #selector(deviceOrientationDidChange(notification:)), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
        
         UIDevice.current.beginGeneratingDeviceOrientationNotifications()
        
    }
    
    func deviceOrientationDidChange(notification:Notification)
    {
        let orientation : UIInterfaceOrientation = UIApplication.shared.statusBarOrientation
        
        if orientation.isLandscape
        {
            playerHeightConstraint.constant = self.view.frame.size.height
            print("landscape")
        } else
        {
            playerHeightConstraint.constant = 180
            print("portrait")
        }
        
    }

    
    override func viewWillDisappear(_ animated: Bool)
    {
        super.viewWillDisappear(animated)
        
        UIDevice.current.endGeneratingDeviceOrientationNotifications()
        
        NotificationCenter.default.removeObserver(self, name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil);

    }

**Comment by shavik** [comment]
Hi @JV17 ,
Have you got solution of your problem yet? reloading issue due to high resolution of iPhone 6 plus while changing frame.

Thanks

**Comment by supermnemonic** [comment]
i successfully implemented fullscreen mode by change the height constraint on rotate. but i got reloading problem because the frame is changed and quality also changed. then i came up to this thread https://github.com/youtube/youtube-ios-player-helper/issues/221 and reloading issue is solved.

this is my step:
1. create and connect (iboutlet) height constraint for video container.
2. change constraint constant on orientation changed. when it goes landscape height = screen height, when it portrait height back to normal.
3. to avoid reloading video, use .cueVideo(byId: startSeconds: suggestedQuality: ) before playing video.

(Swift 3)
```
class VideoDetailController: UIViewController {
    @IBOutlet weak var viewVideoPlayer: YTPlayerView!
    @IBOutlet weak var playerHeightConstraint: NSLayoutConstraint!

    override func viewDidLoad() {
        super.viewDidLoad()

        viewVideoPlayer.delegate = self

        let playerVars = [
            "modestbranding" : "1",
            "controls" : "2",
            "playsinline" : "1",
            "autohide" : "1",
            "showinfo" : "0",
            "autoplay" : "1",
            "fs" : "1",
            "rel" : "0",
            "loop" : "0",
            "enablejsapi" : "1",
            "iv_load_policy": "3"
        ]

        viewVideoPlayer.load(withVideoId: "youtubeId", playerVars: playerVars)
    }

    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        
        coordinator.animate(alongsideTransition: { _ in
            if UIDevice.current.orientation.isLandscape {
                self.playerHeightConstraint.constant = self.view.frame.size.height
                // you can hide statusbar and navbar here
            } else {
                self.playerHeightConstraint.constant = 230
                // you can show again statusbar and navbar here when back to portrait
            }
        }, completion: nil)
    }
}

extension VideoDetailController: YTPlayerViewDelegate {   
    func playerViewDidBecomeReady(_ playerView: YTPlayerView) {
        playerView.cueVideo(byId: "youtubeId", startSeconds: playerView.currentTime(), suggestedQuality: .medium)
        playerView.playVideo()
    }
}


```

**Comment by tirrorex** [comment]
Bumping this, is there any way to trigger a notification when the player goes fullscreen using the control?
I checked the code and i still have no idea of what is happening when a user trigger the control.
Also avplayer has a AVFullScreenViewController, is there any equivalent we can use?
That would make things so much easier.

**Comment by shamithmukundan** [comment]
@tirrorex here you can use UIWindowDidBecomeVisible and UIWindowDidBecomeHidden notifications to observe when the player goes full screen

**Comment by tirrorex** [comment]
Pretty sure i didn't need it anymore, since ios 11 i found a workaround that suits my usecase better.
Thanks anyway :)

**Comment by aysnort** [comment]
By me it didn't work when setting the constraint but this worked
 `self.playerView.frame.size = CGSize(width: self.view.frame.size.width, height: self.view.frame.size.height)`

**Comment by Flatout73** [comment]
You can execute javascript's function `webkitEnterFullScreen()` of video. Check my answer here:
https://stackoverflow.com/questions/59331905/open-iframe-video-in-fullscreen-programmatically/62594780
