### ISSUE TITLE
Apple will stop accepting submissions of app built with this library

### ISSUE THREAD

**Issue by accannis** [youtube/youtube-ios-player-helper#353]
I just submitted an app to App Store that includes this library, and I got the following response:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Is there a fix for this coming? iOS 13 is due any day now…

**Comment by mkoumtzis** [comment]
I have the same issue.

**Comment by damienpraca** [comment]
Same issue aswell here. Apple do not accept submissions because of UIWebview, when a cocoa pod release is planned?

**Comment by emrepun** [comment]
This repo is abandoned guys. Find another solution.

**Comment by mukeshydv** [comment]
Check this project implementing same with WKWebView: [YoutubePlayerView](https://github.com/mukeshydv/YoutubePlayerView)

**Comment by todd-patterson** [comment]
Please update to the official 1.0.0 release, which includes the migration to WKWebView.
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0

I'll go ahead and close this issue now.
