### ISSUE TITLE
Parameter 'quality' not found in the function declaration

### ISSUE THREAD

**Issue by aksthelion** [youtube/youtube-ios-player-helper#357]
Hi,
I'm using this pod with swift 5, xCode 11.2.1 and I'm getting following warnings:

> Parameter 'quality' not found in the function declaration 

in YTPlayerView.h line number 614
` * @param quality YTPlaybackQuality value to suggest for the player.`

There are few other warnings as well. Does anyone know how to get rid of these warnings?

**Comment by todd-patterson** [comment]
The method "setPlaybackQuality" (correlates to line # 614) has been removed in the newest version of this library. The underlying API no longer supports setting playback quality, refer to notes here -
https://developers.google.com/youtube/iframe_api_reference#october-24,-2019

Please update to the 1.0.0 release -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0
