### ISSUE TITLE
[APPLE DEPRECATED UIWEBVIEW] REPLACE WKWEBVIEW

### ISSUE THREAD

**Issue by VietNamBookingApp** [youtube/youtube-ios-player-helper#370]
Dear Admin

Current Apple was DEPRECATED UiWebView  replace WKWebView
if application use uiwebview will be taken down App Store or do not update lasted version
Please update libary

Thanks admin

**Comment by brunodelgado** [comment]
It's already in progress on #362

**Comment by rjkarthi58** [comment]
when will we expect the new version with wkwebview support? @brunodelgado

**Comment by ghazalahk4** [comment]
Hell,
When can we have the new version with WKWEBVIEW support? Please let us know asap @brunodelgado

**Comment by L4grange** [comment]
You can use `pod "youtube-ios-player-helper", :git => 'https://github.com/youtube/youtube-ios-player-helper.git'` in the meantime, but I'm still facing problems in my app, using this library on the master branch with videos not playing.

**Comment by quynv186** [comment]
Hi, please upload to Cocoapods.

**Comment by bre7** [comment]
For SEO sake:

> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by todd-patterson** [comment]
Please update to the 1.0.0 release, which includes the migration to WKWebView.
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0
