### ISSUE TITLE
opens safari instead of loading the video,  Why?

### ISSUE THREAD

**Issue by YYHNobug** [youtube/youtube-ios-player-helper#375]
opens safari instead of loading the video, Why?   

bundleId error?

**Comment by rcvrgs** [comment]
Duplicate of #374. Follow that issue instead. 

Closing this one.

**Comment by todd-patterson** [comment]
Should be fixed in the official 1.0.0 release -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0

Please update to that version.
