### ISSUE TITLE
webview not able to submit application store

### ISSUE THREAD

**Issue by akashRaghani92** [youtube/youtube-ios-player-helper#378]
HellO Team,

Apple has drop web-view support.so not able to submit application using iOS SDK 13 above as third-party using web-view.

So application not submit using this player

**Comment by umerkiani** [comment]
Same Happened with me. I will switch the player to use WkWebView Instead.

**Comment by akashRaghani92** [comment]
@umerkiani I have change lib..NOt able to change in this lib into webkitView...What you have done?

**Comment by austinhjones** [comment]
@rcvrgs Any way you can release the update pod that includes the wkwebview changes?

**Comment by tsulok** [comment]
Use the latest commit hash instead of the release version

`pod "youtube-ios-player-helper", :git => 'https://github.com/youtube/youtube-ios-player-helper.git', :commit => '5882789'`

**Comment by rcvrgs** [comment]
Pod 1.0.0 was just released, includes the WKWebView migration! Thanks for being patient.

**Comment by todd-patterson** [comment]
Thanks @rcvrgs, I'll go ahead and close this issue now.

Here is the 1.0.0 version -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0
