### ISSUE TITLE
How can i remove channel logo, title,more share options, more videos at video ended, etc youtube identifiers?

### ISSUE THREAD

**Issue by SSVernekar** [youtube/youtube-ios-player-helper#379]

**Comment by todd-patterson** [comment]
Sorry, but hiding the UI elements you mentioned is no longer supported as of August 2018. Refer to the release notes -
https://developers.google.com/youtube/player_parameters#august-23,-2018

With regard to "modestbranding", that param only takes effect if the player's controls are disabled -
https://developers.google.com/youtube/player_parameters#controls
