### ISSUE TITLE
Play video (audio of video) in Background  iOS

### ISSUE THREAD

**Issue by adeljodalah** [youtube/youtube-ios-player-helper#38]
Hi 
Im using YouTube Helper Library to play YouTube videos on my iOS application
I just need a way to continue audio (or video) playing in background ,
So when user click on home button i need him to be able to hear the voice
of the video ,
even when he look his device i need to him to be able to control the sound and click next and back button for audio playing .. How i can achieve that on YouTube Helper Library ?
@ikai , @ymotongpoo, @libor

**Comment by dvlpJ** [comment]
Hello. Thank you for your know-how.
Please tell me your solution in detail.

How should I implement your solution code in Xcode ?
Where is it in "YTPlayerView.m" OR "[My custom class].m" OR "AppDelegate.m" ?? 

I referred to your solution and the following site.
However, I didn't know implementation.

<http://blog.5pb.jp/smapho/archives/177>

How i can achieve it.
(Sorry, My Einglish is poor...)

**Comment by adeljodalah** [comment]
Hi @dvlpJ 
1- first of all you have to went to info.plist and add the attribute 
"Required background modes" and add the row for the first item "App plays audio or streams audio/video using AirPlay"

2- after that you have to go to Appdelegete.m file and add those lines on the function 
"- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions"


 NSError *setCategoryError = nil;
    [[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayback error: &setCategoryError];

3- finally to handle the lay,next,back event when the screen locked or the app in background you have to add the following function to Appdelegate.m file

- (void)remoteControlReceivedWithEvent:(UIEvent *)event {
    switch (event.subtype) {
        case UIEventSubtypeRemoteControlPlay:
            // handle it
            break;
        case UIEventSubtypeRemoteControlPause:
            // handle it
            break;
        case UIEventSubtypeRemoteControlNextTrack:
           // handle it
            break;
        case UIEventSubtypeRemoteControlPreviousTrack:
           // handle it
            break;
        default:
            break;
    }
}

Hope that help you to achieve it ..

**Comment by dvlpJ** [comment]
Hi @adeljodalah 
Thank you for your advise very much!!
I did as you taught me, but I was not able to completely solve a problem.
I'm sorry, but could you show me one more time?

When I push the home button or rock button during YTPlayerView instance playing, YTPlayerView music stop.
Then, if I pushed the play button in control center view, the music was played in a background.
I do not want to do stop YTPlayerView music when I push the home button or rock button.

If it's alright with you, please teach me for solutions.

↓My code 
[Xcode 6.1.1]
[info.plist]
"Required background modes  Item0"  :  "App plays audio or streams audio/video using AirPlay"

[AppDelegate.m]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
   NSError *setCategoryError = nil;
    [[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayback error: &setCategoryError];
  return YES;
}

-(void)remoteControlReceivedWithEvent:(UIEvent *)event { switch (event.subtype) {
    case UIEventSubtypeRemoteControlPlay:
        NSLog(@"AppDelegate PLAY remoteControlReceivedWithEvent");
        break;
    case UIEventSubtypeRemoteControlPause:
        NSLog(@"AppDelegate PAUSE UIEventSubtypeRemoteControlPause");
        break;
    case UIEventSubtypeRemoteControlNextTrack:
        NSLog(@"AppDelegate NEXT UIEventSubtypeRemoteControlNextTrack");
        break;
    case UIEventSubtypeRemoteControlPreviousTrack:
        NSLog(@"AppDelegate PREV UIEventSubtypeRemoteControlPreviousTrack");
        break;
    default:
    break;
} }

[ViewController.h]
#import <UIKit/UIKit.h>
#import "YTPlayerView.h"
@interface ViewController : UIViewController<UIWebViewDelegate,YTPlayerViewDelegate>
@property(nonatomic, strong) IBOutlet YTPlayerView *playerView;
@end

[ViewController.m]
#import "ViewController.h"
- (void)viewDidLoad {
    [super viewDidLoad];
   playerVars = @{
                   @"playsinline" : @1,
                   };
    self.playerView.delegate = self;
    [self.playerView loadWithVideoId:@"SxsrupfqVNE" playerVars:playerVars];
}

**Comment by chamroeunbm** [comment]
Thanks you all. That's what I am looking for...

**Comment by airrons** [comment]
ytplayer pause when app enter background also ocurred in my app    could you tell me your solution to this problem .

**Comment by rakii** [comment]
@adeljodalah  
ytplayer pauses when app enter background. 
and can be resume playing after i hit play from Notification Centre. 
Need to play in background. 

Thanks

**Comment by tijwelch** [comment]
Thanks @adeljodalah 

Would you mind confirming whether the audio continues to play when you hit the home button? I am seeing the same thing as @chamroeunbm (the user has to manually resume by pressing play from the Control Center https://support.apple.com/en-us/HT202769).

Much appreciated!

**Comment by adeljodalah** [comment]
@tijwelch  its stop playing when we hit home button ,but what i did is force this by background thread and make the video continuo playing if the status is "pause" .
The pause functionality just applied when the pause button hit , otherwise i discard the pause functionality .. by this way i make it work

**Comment by MiaShopgal** [comment]
@adeljodalah do you mean by this ?
- (void)playerView:(YTPlayerView *)ytPlayerView didChangeToState:(YTPlayerState)state {
     switch(state){
          kYTPlayerStatePaused:
                [ytPlayerView playVideo];
     }
}

**Comment by adeljodalah** [comment]
@MiaShopgal yes exactly

**Comment by mfclarke** [comment]
Unfortunately this doesn't work for me on iOS 8.4.1. As I press the home button the following happens:

1. Player pauses
2. Player plays after delegate ```didChangeToState``` is hit
3. Player goes into buffering state

I assume iOS cuts off network traffic for the app since it's backgrounded?

**Comment by MiaShopgal** [comment]
have you declared your app’s supported background tasks ?
[Declaring Your App’s Supported Background Tasks](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW1)

**Comment by ahallora** [comment]
Working in iOS 9, however the music still pauses for a second when going to background (pressing the Home button) but resumes playback quickly thereafter. 

I got it working by setting my project->capabilities->background mode to ON and Audio and Airplay and adding this code to my appDelegate:

```
#import <AVFoundation/AVFoundation.h>
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSError *sessionError = nil;
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:&sessionError];
...
 return TRUE;
}
```
and in my viewcontroller for the YouTube player:
```
- (void)playerView:(YTPlayerView *)playerView didChangeToState:(YTPlayerState)state {
    switch (state) {
        case kYTPlayerStatePaused:
            [self.playerView playVideo];
            break;
        default:
            break;
    }
}
```

It would be great if there were no pause at all, but I'm not skilled enough to pull that off... Maybe somebody got a clever trick? :smile:

**Comment by rinyfo4** [comment]
Hey, does anyone have this translated in swift? I'm new to iOS development and having a hard time understanding the objective-c... Any and all help is GREATLY appreciated!

**Comment by alejomendoza** [comment]
@ahallora where did you place the playerView method? I tried adding it on YTPlayerView.m . I wasn't able to get this working. I'm using React Native and I don't have a lot of experience using Objective C. I'm also using https://github.com/paramaggarwal/react-native-youtube

**Comment by naveen488** [comment]
Hi every one,

i am jr.ios developer . present i am working on youtube API. It is almost completed. i have one issue i.e when i am playing one youtube video while lock the screen it is playing well but my progressBar not 
working. please provide code or solution for me 
Can any one help me? sry for my poor english............

**Comment by bhavinspaceo** [comment]
Hi Friends

How to show poster image with audio on lock screen. Any idea?

**Comment by hiteshtrivedi** [comment]
Hi Friends

How to show poster image with audio on lock screen. Any idea?

**Comment by naveen488** [comment]
Hi,

yes I know that one dear.

**Comment by hiteshtrivedi** [comment]
Naveen, Can you please provide source code or hint. How we can do that.

Thanks in Advance.

**Comment by doriansgithub** [comment]
I have the opposite problem, YouTube is demanding that the video does NOT play while in the lock screen.  It is apparently against their API rules/regulations.  For those trying to achieve that, you'll be emailed by Apple telling you to comply with YouTube's demands.  Apple will not ban your app, but YouTube might eventually block the API from your app.

**Comment by ahallora** [comment]
Technically speaking YouTube is a VIDEO streaming service so naturally the video must be visible in order to also hear the audio. Therefore, locking the phone (turning off the screen) should also stop the video playback. 

In order to comply with YouTube TOS and Apple guidelines you need to display the video - and stop it from playing when locking the screen. Sadly, no background playback of YouTube videos for you. 😢

**Comment by doriansgithub** [comment]
Ok, that makes is clearer.  We'll be fixing that today.  Thanks for the info.

**Comment by Cu-Toof** [comment]
@mfclarke I have the same problem:
- Player pauses
- Player plays after delegate didChangeToState is hit
- Player goes into buffering state
In buffering state, I play Player, so when app goes into background state, video is interrupted
I hope to receive bits of advice for this problem. Thank you.

**Comment by jassionly4u** [comment]
@mfclarke : Yes this is true. it goes into the background state. Did you find any solution for that.

**Comment by doriansgithub** [comment]
If you do not pause the video, YouTube will ban your app from the AppStore.

**Comment by kikumarueiji81** [comment]
@doriansgithub Hey Dorian, If that is the case how is Musi app able to do it? PFB the link for the same 

https://itunes.apple.com/us/app/musi-simple-music-streaming/id591560124?mt=8

**Comment by doriansgithub** [comment]
They haven't been caught.  We were caught and were taking off the App store until we implemented a pause when going to background.

**Comment by kikumarueiji81** [comment]
@doriansgithub I feel the same about taking the apps down for this reason but how are these guys able to hide it from 2 years ?

**Comment by doriansgithub** [comment]
Not sure, but they might still get caught.  Are you sure you can lock the screen and still play the music?

**Comment by kikumarueiji81** [comment]
I’m not sure either

**Comment by User2004** [comment]
https://webappcodes.com/play-video-in-objective-c

Write above link code for play video in objective C

**Comment by KartikeyaRokde** [comment]
Hi, does anyone know does rave.io manage to do that with YouTube's policy not allowing to play in the background? The Rave app is on the AppStore since around 4 years!

**Comment by ehy12345** [comment]
Has anyone figured out how to make this audio work in the background consistently on more recent versions of iOS (14 & 15)?
