### ISSUE TITLE
In iOS13.5, there was a bug in the behavior of the embedded player's play and voice buttons.

### ISSUE THREAD

**Issue by odapivot** [youtube/youtube-ios-player-helper#382]
The view of the player is placed on the tableViewCell in the application.
Autoplay is turned on.
When you press the play button or voice button of the player, it immediately returns to the original state.
Press play to stop.
If you press the voice button to cancel mute, it will immediately return to the mute state.

**Comment by asowers1** [comment]
I'm seeing a similar issue, but in my case we're using `playsinline: 1` and the resume/pause button on the player is returning to the initial state after you press the button.

**Comment by odapivot** [comment]
https://github.com/youtube/youtube-ios-player-helper/issues/374

After confirming with the latest master,
Of the controller during inline playback
The bug that the state of the play button and volume button immediately returns to the original state is no longer reproduced.

This time, the seek bar disappears,
When you tap the area of ​​the seek bar,
A list of different videos is displayed with a flickering. It behaves like a bug.

This is a problem on the Youtube player side, and it seems not to be a problem that can be solved here.

The display of the controller of the player seems to differ depending on the iOS version. Isn't it possible to return to the seek bar display in iOS15.1.

**Comment by sukidhar** [comment]
> I'm seeing a similar issue, but in my case we're using `playsinline: 1` and the resume/pause button on the player is returning to the initial state after you press the button.

I am having same issue.. hope this gets fixed soon..

**Comment by odapivot** [comment]
I solved it here.
https://github.com/youtube/youtube-ios-player-helper/issues/387

**Comment by todd-patterson** [comment]
Based on the most recent comment from @odapivot, sounds like this was resolved in #387. Refer to additional details on that ticket, I'll go ahead and close this one.
