### ISSUE TITLE
MKWebView Not effected when install latest version 0.1.6

### ISSUE THREAD

**Issue by sallamy** [youtube/youtube-ios-player-helper#383]
MKWebView Not effected when install latest version 0.1.6
still have same uiwebview

**Comment by tsulok** [comment]
It is not released yet. Version 0.1.6 refers to a way older version.

Checkout by using a hash in your pod file to get the latest version:

`pod "youtube-ios-player-helper", :git => 'https://github.com/youtube/youtube-ios-player-helper.git', :commit => '5882789'`

**Comment by todd-patterson** [comment]
Please update to the 1.0.0 release, which includes the migration to WKWebView.
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.0
