### ISSUE TITLE
 Inline player display is not optimized for smartphones on iOS 13.5 and later

### ISSUE THREAD

**Issue by odapivot** [youtube/youtube-ios-player-helper#387]
The display of the player inline is strange in iOS13.5 or later.

The size of the video title is small and hard to see
I can't tap the share button, etc.

If the seek bar of the player controller is not displayed and you tap the area of ​​the seek bar, the related video is displayed for a moment, but it is not the UI that the user can operate

The display is not optimized for smartphones as a whole.

**Comment by odapivot** [comment]
Now it looks like it did before! Great work!

**Comment by todd-patterson** [comment]
Thanks for reporting the issue, this has been fixed in release 1.0.1 -
https://github.com/youtube/youtube-ios-player-helper/releases/tag/1.0.1
