### ISSUE TITLE
Auto layout issue using iOS 8

### ISSUE THREAD

**Issue by dpbataller** [youtube/youtube-ios-player-helper#39]
I'm having troubles with auto layout and iOS 8 because the player not resize correctly.

![screen shot 2014-10-21 at 16 43 14](https://cloud.githubusercontent.com/assets/1285920/4720471/4c6f68c0-5931-11e4-9417-d2c0e832ad1b.png)
![screen shot 2014-10-21 at 16 43 45](https://cloud.githubusercontent.com/assets/1285920/4720472/4c813564-5931-11e4-99d9-bdc2d82c30e6.png)

**Comment by drewpts** [comment]
@InderKumarRathore thanks man!!!!

**Comment by InderKumarRathore** [comment]
:relaxed:

**Comment by iosrider** [comment]
Thanks man. You have saved us.
