### ISSUE TITLE
iOS YTPlayerView Throws AutoLayout Constraint Exceptions on iOS 8 in Full Screen Mode

### ISSUE THREAD

**Issue by ccocchiaro** [youtube/youtube-ios-player-helper#40]
YTPlayerView has not been updated to support iOS 8, specifically for iPhone 6/6 Plus devices.  As a result, it has a number of issues related to auto layout constraints that cause it to intermittently crash, restart videos with time ranges, or fail when attempting to dismiss it when it's displayed in a full screen view controller.  Aside from these issues, and as previously reported, it never calls the delegate receivedError method for missing or private videos.  Is there any plan to update this iOS component in the near-term?

Here are the constraint issues being thrown when it transitions to full screen mode:

2014-10-29 10:22:23.753 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x174280140 UIImageView:0x1701f7100.centerX == AVUnsupportedContentIndicatorView:0x174188880.centerX>",
    "<NSLayoutConstraint:0x1742801e0 H:|-(>=10)-[UIImageView:0x1701f7100]   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x174280a00 H:|-(0)-[AVUnsupportedContentIndicatorView:0x174188880]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280a50 H:[AVUnsupportedContentIndicatorView:0x174188880]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x174280140 UIImageView:0x1701f7100.centerX == AVUnsupportedContentIndicatorView:0x174188880.centerX>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.755 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170283250 UIView:0x1701897f0.centerX == AVExternalPlaybackIndicatorView:0x1701aeb60.centerX>",
    "<NSLayoutConstraint:0x1702832f0 H:|-(>=10)-[UIView:0x1701897f0]   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x174280cd0 H:|-(0)-[AVExternalPlaybackIndicatorView:0x1701aeb60]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280d20 H:[AVExternalPlaybackIndicatorView:0x1701aeb60]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170283250 UIView:0x1701897f0.centerX == AVExternalPlaybackIndicatorView:0x1701aeb60.centerX>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.756 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1702832f0 H:|-(>=10)-[UIView:0x1701897f0]   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x170283340 H:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x174280cd0 H:|-(0)-[AVExternalPlaybackIndicatorView:0x1701aeb60]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280d20 H:[AVExternalPlaybackIndicatorView:0x1701aeb60]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170283340 H:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.758 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1742801e0 H:|-(>=10)-[UIImageView:0x1701f7100]   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x1702829e0 H:[UIImageView:0x1701f7100]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x174280a00 H:|-(0)-[AVUnsupportedContentIndicatorView:0x174188880]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280a50 H:[AVUnsupportedContentIndicatorView:0x174188880]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1702829e0 H:[UIImageView:0x1701f7100]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.760 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170282ad0 UIImageView:0x1741f2c00.centerX == AVAudioOnlyIndicatorView:0x174189990.centerX>",
    "<NSLayoutConstraint:0x170282c10 H:|-(>=10)-[UIImageView:0x1741f2c00]   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x174280b40 H:|-(0)-[AVAudioOnlyIndicatorView:0x174189990]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280b90 H:[AVAudioOnlyIndicatorView:0x174189990]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170282ad0 UIImageView:0x1741f2c00.centerX == AVAudioOnlyIndicatorView:0x174189990.centerX>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.762 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170282c10 H:|-(>=10)-[UIImageView:0x1741f2c00]   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x170282c60 H:[UIImageView:0x1741f2c00]-(>=10)-|   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x174280b40 H:|-(0)-[AVAudioOnlyIndicatorView:0x174189990]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280b90 H:[AVAudioOnlyIndicatorView:0x174189990]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x1742808c0 H:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x174280910 H:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x170285370 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170282c60 H:[UIImageView:0x1741f2c00]-(>=10)-|   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.764 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1702832a0 UIView:0x1701897f0.centerY == AVExternalPlaybackIndicatorView:0x1701aeb60.centerY + 10>",
    "<NSLayoutConstraint:0x1702833e0 V:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x170283660 V:|-(0)-[UIImageView:0x1701f7300]   (Names: '|':UIView:0x1701897f0 )>",
    "<NSLayoutConstraint:0x1702836b0 V:[UIImageView:0x1701f7300]-(20)-[UILabel:0x1010a6660]>",
    "<NSLayoutConstraint:0x170283700 V:[UILabel:0x1010a6660]-(0)-[UILabel:0x1010a68d0]>",
    "<NSLayoutConstraint:0x170283750 V:[UILabel:0x1010a68d0]-(0)-|   (Names: '|':UIView:0x1701897f0 )>",
    "<NSLayoutConstraint:0x174280d70 V:|-(0)-[AVExternalPlaybackIndicatorView:0x1701aeb60]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280dc0 V:[AVExternalPlaybackIndicatorView:0x1701aeb60]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1702836b0 V:[UIImageView:0x1701f7300]-(20)-[UILabel:0x1010a6660]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.767 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1702832a0 UIView:0x1701897f0.centerY == AVExternalPlaybackIndicatorView:0x1701aeb60.centerY + 10>",
    "<NSLayoutConstraint:0x1702833e0 V:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x174280d70 V:|-(0)-[AVExternalPlaybackIndicatorView:0x1701aeb60]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280dc0 V:[AVExternalPlaybackIndicatorView:0x1701aeb60]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1702832a0 UIView:0x1701897f0.centerY == AVExternalPlaybackIndicatorView:0x1701aeb60.centerY + 10>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.769 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x174280190 UIImageView:0x1701f7100.centerY == AVUnsupportedContentIndicatorView:0x174188880.centerY + 10>",
    "<NSLayoutConstraint:0x170282a80 V:[UIImageView:0x1701f7100]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x174280aa0 V:|-(0)-[AVUnsupportedContentIndicatorView:0x174188880]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280af0 V:[AVUnsupportedContentIndicatorView:0x174188880]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x174280190 UIImageView:0x1701f7100.centerY == AVUnsupportedContentIndicatorView:0x174188880.centerY + 10>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.771 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170282b70 UIImageView:0x1741f2c00.centerY == AVAudioOnlyIndicatorView:0x174189990.centerY + 10>",
    "<NSLayoutConstraint:0x170282d00 V:[UIImageView:0x1741f2c00]-(>=10)-|   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x174280be0 V:|-(0)-[AVAudioOnlyIndicatorView:0x174189990]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280c30 V:[AVAudioOnlyIndicatorView:0x174189990]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170282b70 UIImageView:0x1741f2c00.centerY == AVAudioOnlyIndicatorView:0x174189990.centerY + 10>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.774 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170283390 V:|-(>=10)-[UIView:0x1701897f0]   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x1702833e0 V:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>",
    "<NSLayoutConstraint:0x174280d70 V:|-(0)-[AVExternalPlaybackIndicatorView:0x1701aeb60]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280dc0 V:[AVExternalPlaybackIndicatorView:0x1701aeb60]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1702833e0 V:[UIView:0x1701897f0]-(>=10)-|   (Names: '|':AVExternalPlaybackIndicatorView:0x1701aeb60 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.776 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170282a30 V:|-(>=10)-[UIImageView:0x1701f7100]   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x170282a80 V:[UIImageView:0x1701f7100]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>",
    "<NSLayoutConstraint:0x174280aa0 V:|-(0)-[AVUnsupportedContentIndicatorView:0x174188880]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280af0 V:[AVUnsupportedContentIndicatorView:0x174188880]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170282a80 V:[UIImageView:0x1701f7100]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x174188880 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2014-10-29 10:22:23.777 MomentumD[4562:1499764] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x170282cb0 V:|-(>=10)-[UIImageView:0x1741f2c00]   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x170282d00 V:[UIImageView:0x1741f2c00]-(>=10)-|   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>",
    "<NSLayoutConstraint:0x174280be0 V:|-(0)-[AVAudioOnlyIndicatorView:0x174189990]   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280c30 V:[AVAudioOnlyIndicatorView:0x174189990]-(0)-|   (Names: '|':UIView:0x174186a70 )>",
    "<NSLayoutConstraint:0x174280960 V:|-(0)-[UIView:0x174186a70]   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1742809b0 V:[UIView:0x174186a70]-(0)-|   (Names: '|':AVPlayerView:0x1701893e0 )>",
    "<NSLayoutConstraint:0x1702853c0 'UIView-Encapsulated-Layout-Height' V:[AVPlayerView:0x1701893e0(1)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170282d00 V:[UIImageView:0x1741f2c00]-(>=10)-|   (Names: '|':AVAudioOnlyIndicatorView:0x174189990 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by Kowaio** [comment]
Hi @ccocchiaro,

I'm experiencing the same issue in my case when I close the fullscreen mode by tapping the "OK" button. A lot of unsatisfying constraint pops out in the log and I'm experiencing weird behaviors throughout my app afterwards.

If you've found a fix since your first post, it'd be great!

Thanks a lot!

Best,
K

**Comment by dfmuir** [comment]
I am also experiencing this issue.

**Comment by kevosauce** [comment]
I'm getting this as well, but I see the issue has been closed. Is there a workaround?

**Comment by pjamroz** [comment]
I'm in similar situation right now. Is there any way to solve this?
