### ISSUE TITLE
Deployment target increased to iOS 10

### ISSUE THREAD

**Issue by rholstad** [youtube/youtube-ios-player-helper#400]
Thank you for updating the library to use WKWebView! However, I noticed that the minimum deployment target was also bumped up to iOS 10. Is there a specific reason for going to iOS 10 since WKWebView is available from iOS 8+? I still need to support iOS 9, so I have forked the repo and modified the podspec to iOS 9 and it is building fine.

**Comment by todd-patterson** [comment]
Hi there,
This was part of the normal process of aging-off legacy OS versions. The library may compile and run successfully against iOS 9, but the very low percent of iOS devices still running iOS 9 doesn't justify continued support.

The latest [App Store data](https://developer.apple.com/support/app-store/) from 2020-06-17 mentions that only 6% of iOS devices are running <= iOS 11. See screenshot -

<img width="1680" alt="Screen Shot 2020-07-06 at 11 14 29 PM" src="https://user-images.githubusercontent.com/15205117/86726593-8ea4d200-bfdf-11ea-917a-6ffcf828f717.png">

Compare to the historical data from a [TechCrunch article](https://techcrunch.com/2018/08/23/twitter-ends-support-for-ios-9-and-lower/) published on 2018-08-23, which mentions:

> Apple’s data indicates only 5% percent of users are still on iOS 9 or below


See screenshot -
<img width="1680" alt="Screen Shot 2020-07-06 at 11 16 06 PM" src="https://user-images.githubusercontent.com/15205117/86728326-366ecf80-bfe1-11ea-89aa-3124cf202bf5.png">

Even though the article is specifically about Twitter dropping support for iOS 9, the referenced App Store data about percent of devices running iOS 9 or lower still applies.

Given these two data points and the normal upgrade rate of iOS users, we can reasonably infer that devices running <= iOS 9 is <= 1-2%. We think this is a very reasonably cut-off for dropping support.

If you haven't already, it is probably worthwhile to discuss with your team / company / org whether there is meaningful ROI for you to continue supporting iOS 9.
