### ISSUE TITLE
[LIB youtube-ios-player-helper] - VER 1.0.2 DONT WORKING

### ISSUE THREAD

**Issue by hoangduong536** [youtube/youtube-ios-player-helper#402]
HI ADMIN

VER 1.0.2 DONT WORKING,  VER CURRENT: 0.1.6 DONT HAVE WEBKIT
![image](https://user-images.githubusercontent.com/18218059/87748077-28aa1d00-c81f-11ea-9ce9-debba13a8920.png)

**Comment by denkeni** [comment]
Check out https://github.com/youtube/youtube-ios-player-helper/issues/400. They decided to drop support for iOS 9, but you can fork the project to support iOS 9.

**Comment by jhicks-ddm** [comment]
Ah, thanks for pointing that out.

**Comment by rcvrgs** [comment]
Just confirming that the library only supports iOS 10+ versions.

**Comment by todd-patterson** [comment]
In addition to my comment on #400, iOS 14 was since released on 2020-09-16. This makes iOS 9 even more legacy, being 5 major versions behind. Continuing to support iOS 9 has diminishing returns and we believe is not the right investment of time.

Closing this issue.
