### ISSUE TITLE
No such module 'youtube_ios_player_helper'

### ISSUE THREAD

**Issue by aneena-thomas** [youtube/youtube-ios-player-helper#408]
Showing No such module 'youtube_ios_player_helper' after installing 1.0.2 in swift project

**Comment by rcvrgs** [comment]
Hi, thank you for opening an issue for your inquiry.

We need more info to troubleshoot this. #402 seems to be the same or similar issue you're encountering.

- This library only supports iOS 10+ versions.
- Make sure you are a recent Cocoapods version, for example. 2.6.3+.

If you still encounter the issue, let us know with all the info you can provide.

**Comment by todd-patterson** [comment]
Closing stale issue.

**Comment by oleksandryevdokymov** [comment]
The same issue

**Comment by riazhazan** [comment]
same issue in Xcode 13.4.1 Mac OS Monterey Apple M1 chip

**Comment by raghubalakrishnann** [comment]
I'm also facing the same kind of issue with mac m1 - /Pods/youtube-ios-player-helper/youtube-ios-player-helper/Assets.bundle: No such file or directory. Any solution ?

**Comment by BraveEvidence** [comment]
same issue
