### ISSUE TITLE
iOS YTPlayerView Intermittently Resets Video After 5 Seconds And Start Playback Over

### ISSUE THREAD

**Issue by ccocchiaro** [youtube/youtube-ios-player-helper#42]
The iOS YTPlayerView, when displayed in full screen mode, intermittently resets videos after 5 seconds when a "start" and "end" parameters are used to play a segment of a video.  The order of state changes are:

state = kYTPlayerStateBuffering
state = kYTPlayerStatePlaying
...
playback occurs for 5 seconds
...
state = kYTPlayerStateBuffering
state = kYTPlayerStatePlaying
...
playback restarts from configured "start" parameter
...

YTPlayerView parameters used are:

    NSMutableDictionary *playerParams = [[NSMutableDictionary alloc] init];
    [playerParams setObject : @"0" forKey : @"playsinline"];
    [playerParams setObject : @"1" forKey : @"autoplay"];
    [playerParams setObject : @"0" forKey : @"rel"];
    [playerParams setObject : @"1" forKey : @"modestbranding"];
    [playerParams setObject : @"1" forKey : @"fs"];
        
    if (_endSecond > _startSecond)
    {
        [playerParams setObject : [NSString stringWithFormat : @"%li", (long)_startSecond] forKey : @"start"];
        [playerParams setObject : [NSString stringWithFormat : @"%li", (long)_endSecond] forKey : @"end"];
    }
    else
    {
        [playerParams setObject : [NSString stringWithFormat : @"%li", (long)_startSecond] forKey : @"start"];
    }
    
    [_ytPlayerView loadWithVideoId : _videoId playerVars : playerParams];

**Comment by Anislav** [comment]
This defect is exactly the one that I am experiencing and that I even recorded and reported in the referenced above issue. 
I just wonder whether this issue is closed because it is not reproducible by @iulukaya  or because it is a defect in the YouTube iframe player, not in this iOS wrapper.
