### ISSUE TITLE
native video control bar not available in iOS 14.5

### ISSUE THREAD

**Issue by jeongrok-kim** [youtube/youtube-ios-player-helper#431]
This problem only occurs in iOS 14.5 using native control bar _(seek bar)_.

When tap the video player area, the video control bar appears for a moment and then disappears immediately.
This can be reproduced by modifying the `playerVar` of `youtube-player-ios-example` as follows:

in https://github.com/youtube/youtube-ios-player-helper/blob/master/Project/youtube-player-ios-example/youtube-player-ios-example/SingleVideoViewController.m#L26
```diff
   // For a full list of player parameters, see the documentation for the HTML5 player
   // at: https://developers.google.com/youtube/player_parameters?playerVersion=HTML5
   NSDictionary *playerVars = @{
-      @"controls" : @0,
+      @"controls" : @1,
       @"playsinline" : @1,
       @"autohide" : @1,
       @"showinfo" : @0,
```

**Environment**
- Xcode 12.5
- iPhone Simulator iOS 14.5

It may be an issue on the iFrame api side, but can anyone check it out?

https://user-images.githubusercontent.com/7258627/116855662-b6cb8480-ac34-11eb-9bc8-95de1042b0cc.mov

Thanks in advance.

**Comment by farismhmd1** [comment]
i am also experiencing similiar issue

**Comment by Heligo-R** [comment]
I have the same issue on iPhone 12 iOS 14.6

**Comment by nassifbasheer** [comment]
hi,

I am experiencing a similar issue, controls are working fine in emulators but when running on actual device. it is not showing the controls. Has anyone found a fix for this

**Comment by harri35** [comment]
I have the same issue in out app.

**Comment by nassifbasheer** [comment]
has anyone able to fix this issue

**Comment by pedronveloso** [comment]
Same issue here.

**Comment by takuoka** [comment]
+1

**Comment by famio** [comment]
+1

**Comment by Tibimac** [comment]
+1
This issue duplicated this one : https://github.com/youtube/youtube-ios-player-helper/issues/391

**Comment by ykws** [comment]
@jeongrok-kim Hi, have you resolved this issue yet?
Now I worked it on Xcode**13**(not **12**), please check it again.

https://user-images.githubusercontent.com/5770480/135305530-12f5fbb3-7552-4753-b0b4-0b5165c9888e.mp4

**Comment by jeongrok-kim** [comment]
@ykws 
Thank you. I also checked.
It appears that the YouTube iFrame Player has been updated to use its own control UI instead of the iOS Native Control.
So somehow the problem was solved. 😅
