### ISSUE TITLE
iOS embed in WKWebView earned error

### ISSUE THREAD

**Issue by YouZoudeFish** [youtube/youtube-ios-player-helper#433]
Here is the app sence:
VC A loads WKWebView(webview)，webview loads urlRequest to play a video. But when video starts playing, Xcode console outputs errors like this:
![image](https://user-images.githubusercontent.com/13774334/123899397-b2ec8200-d999-11eb-9f32-1e7f14e59ba3.png)
but it does not affect video to play, it affects when App entering backgroud, and reactive in foreground. the effect is the video can't continue playing.
So...How to resolve this problem......
Thanks for comment firstly......

**Comment by YouZoudeFish** [comment]
The develop environment is: Xcode 12.3 & iOS 14.3
Has tried add : configuration.mediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypeNone;
but it doesn't work.

**Comment by YouZoudeFish** [comment]
Finally, find a way to solved the problem....

**Comment by misterhtmlcss** [comment]
@YouZoudeFish dude what was the solution? Saying you solved it, but not saying how is really harsh. Please share if you still recall.
