### ISSUE TITLE
Is the frame rate of the playing video available?

### ISSUE THREAD

**Issue by inexcii** [youtube/youtube-ios-player-helper#453]
Hi, this is generally a question rather than an issue.
Is there a way to retrieve the frame rate, aka FPS(Frames Per Second), of the playing YouTube video by this framework?
I'm creating an app based on the frame rate of the YouTube video and would be appreciated if in some way I can get(or at least generally assume) the frame rate of the playing video.
Thanks.

**Comment by brol1dev** [comment]
The library doesn't offer an API to retrieve FPS of the video playing. Sorry about that.

**Comment by inexcii** [comment]
Thank you for the reply. I see.
