### ISSUE TITLE
Video in Landscape Mode

### ISSUE THREAD

**Issue by Ravinder-webonise** [youtube/youtube-ios-player-helper#463]
I start to playing video in landscape, but when I rotate to portrait, the player will follow the orientation.
Anyone know how to make the player only playing in landscape mode?

**Comment by brol1dev** [comment]
Hi @Ravinder-webonise ,

This should be possible to do with custom code. You can make the current visible ViewController not autorotate with Apple APIs. This is one example that should work: [shouldAutorotate](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621419-shouldautorotate?language=objc).

I'll close the ticket but feel free to open a new one if this issue pertains more to this video library.
