### ISSUE TITLE
Ads Opening in Safari Without User Interaction?

### ISSUE THREAD

**Issue by JALsnipe** [youtube/youtube-ios-player-helper#54]
I've found when playing back some YouTube videos using this library, before the video even starts, Safari will open to a blank ad page.  I've been able to reproduce this with this video: https://www.youtube.com/watch?v=ydv6j9CrPGo

Has anyone else experience this?  Is there a better way to handle ad interruptions besides forcing the user out of the app and into Safari?

**Comment by dictav** [comment]
+1

I fixed this problem in this way: https://github.com/dictav/youtube-ios-player-helper/commit/f10de449486227eae849e68c067d1e32a8740be7

**Comment by JALsnipe** [comment]
Nice this is great, thanks!  Wouldn't this violate YouTube's Terms of Service though?

**Comment by JALsnipe** [comment]
@iulukaya What is the YouTube-sanctioned way to handle ads redirecting the user out of your app?

**Comment by khaledalissa** [comment]
I fixed it by adding another condition in the method shouldStartLoadWithRequest() that is located in the file YTPlayerView.m. The condition should intercept requests made to pubads.g.doubleclick.net.

```objectivec
else if ([request.URL.host isEqual: @"pubads.g.doubleclick.net"])
{
         return NO; 
} 
```

**Comment by khaledalissa** [comment]
I fixed it by adding another condition in the method **shouldStartLoadWithRequest()** that is located in the file **YTPlayerView.m**. The condition should intercept requests made to *pubads.g.doubleclick.net*.

```objectivec
else if ([request.URL.host isEqual: @"pubads.g.doubleclick.net"])
{
         return NO; 
} 
```

**Comment by JALsnipe** [comment]
Looks like @dictav's way of handling this has been sanctioned by @iulukaya and has been merged into the master branch.

https://github.com/youtube/youtube-ios-player-helper/pull/58

Closing this issue.

**Comment by stanislaw** [comment]
Could you please also update podspec so new version would have this change onboard? Thanks!
