### ISSUE TITLE
Followed the instructions but the sample code doesn't compile -- Am I missing something?

### ISSUE THREAD

**Issue by shyamalschandra** [youtube/youtube-ios-player-helper#72]
![image](https://cloud.githubusercontent.com/assets/9545735/5915565/c4bcf1ca-a5cc-11e4-8df9-ee4067dd8785.png)

FYI...

What should I do?

**Comment by rakii** [comment]
Run the command --> pod install

**Comment by shyamalschandra** [comment]
Thanks!  Works!
