### ISSUE TITLE
Autoplay doesn't seem to work

### ISSUE THREAD

**Issue by anotherandersson** [youtube/youtube-ios-player-helper#8]
Hi,

I'm having some problems with the autoplay feature.
Has this something to do with apple or am I doing something wrong here?

This is the method I use to load the video, parameters like ”playsinline” and ”showinfo” seems to work fine.

- (void)playVideoWithId:(NSString *)videoId {

        NSDictionary *playerVars = @{
                                     @"playsinline" : @1,
                                     @"autoplay" : @1,
                                     @"showinfo" : @0,
                                     @"rel" : @0,
                                     @"modestbranding" : @1,
                                     };
        
        [self.playerView loadWithVideoId:videoId playerVars:playerVars];

}

Thanks in advance.

**Comment by arno608rw** [comment]
Yes.

**Comment by mohdhaider** [comment]
Works great, Thanks. 👍

**Comment by dennisvera** [comment]
hello! I've been trying to get a youtube video to autoplay with YTPlayerView with no success. It hows on my view controller but its does not autoplay. my code is on swift 3. any help appreciated!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let playerVars = ["playsinline" : 0,
                          "autoplay" : 1,
                          "showinfo" : 0,
                          "rel" : 0,
                          "controls" : 0]
        
        videoPlayer.load(withVideoId: movieVideoKey, playerVars: playerVars)
        playerViewDidBecomeReady()
    }
    
    func playerViewDidBecomeReady() {
        videoPlayer.playVideo()
    }

**Comment by edpenano** [comment]
@dennisvera were you ever able to figure this out?

**Comment by apersaud** [comment]
For those trying to find the answer and getting to the bottom of this thread, @winterlovesong has the correct answer for auto playing but requires a bit more explanation.

1) Make sure you add the controller as the delegate of player view and implement `YTPlayerViewDelegate` protocol.
2) Implement `func playerViewDidBecomeReady(_ playerView: YTPlayerView)`
3) Call `playerView.playVideo()` in that method to start playing the video

```swift
// Example
class MyPlayerController : UIViewController {

   override func viewDidLoad() {
       super.viewDidLoad()
       // Set the delegate property
       playerView.delegate = self

       let playerVars = ["showinfo" : 0] /// your vars
       playerView.load(withVideoId: "someId", playerVars: playerVars)
    }
}

extension MyPlayerController : YTPlayerViewDelegate {

    func playerViewDidBecomeReady(_ playerView: YTPlayerView) {
        // call play video when the player is finished loading.
        playerView.playVideo()
    }
}
```
