### ISSUE TITLE
Related videos showing on production

### ISSUE THREAD

**Issue by dolarsrg** [youtube/youtube-ios-player-helper#83]
Hi every one.

I'm using this code:
``` 
        NSDictionary *playerVars = @{

                                 @"autohide" : @0,

                                 @"autoplay" : @1,

                                 @"enablejsapi" : @1,

                                 @"fs" : @0,

                                 @"rel" : @0,

                                 @"showinfo" : @0,

                                 @"modestbranding" : @1

                                 };

        [youTubePlayerView loadWithVideoId:videoId playerVars:playerVars];
 ```
When testing my app in development environment everything is working fine: no related videos are shown after playback. But when the app is published at iOS AppStore the view is showing the related links after playback.

How is this happening? Is something going wrong?

**Comment by dolarsrg** [comment]
Now is not happening. Maybe youtube was ignoring the param temporarily!

**Comment by Kowaio** [comment]
Nice to know.... I recently uploaded an update of my app with YT viewer too. I'll let you know if I have the same issue. I hope not :)
