### ISSUE TITLE
Not work on iOS8

### ISSUE THREAD

**Issue by chamroeunbm** [youtube/youtube-ios-player-helper#99]

**Comment by chamroeunbm** [comment]
Hi,
It used to work on iOS7. now in my iOS8, Nothing appear. no video is played.

**Comment by JALsnipe** [comment]
Can you show us some code?  I've been able to use this no problem with the iOS 8 SDK.

**Comment by chamroeunbm** [comment]
Sorry, it was my mistake. I migrate the code and it conflict with my existing code.
